CREATE DATABASE IF NOT EXISTS e_appointment CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE e_appointment;

CREATE TABLE IF NOT EXISTS patients (
    patient_id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS doctors (
    doctor_id INT AUTO_INCREMENT PRIMARY KEY,
    doctor_name VARCHAR(100) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    experience_years INT NOT NULL DEFAULT 0,
    phone VARCHAR(20) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    consultation_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    UNIQUE KEY uk_doctor_email (email)
);

CREATE TABLE IF NOT EXISTS specialization_keywords (
    keyword_id INT AUTO_INCREMENT PRIMARY KEY,
    specialization VARCHAR(100) NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    UNIQUE KEY uk_specialization_keyword (specialization, keyword),
    KEY idx_keyword (keyword)
);

INSERT IGNORE INTO specialization_keywords (specialization, keyword) VALUES
('Cardiologist', 'heart'),
('Cardiologist', 'cardio'),
('Cardiologist', 'cardiac'),
('Cardiologist', 'chest pain'),
('Cardiologist', 'bp'),
('Cardiologist', 'blood pressure'),
('Cardiologist', 'hypertension'),
('Dermatologist', 'skin'),
('Dermatologist', 'acne'),
('Dermatologist', 'pimple'),
('Dermatologist', 'pimples'),
('Dermatologist', 'rash'),
('Dermatologist', 'eczema'),
('Dermatologist', 'psoriasis'),
('Orthopedic Surgeon', 'bone'),
('Orthopedic Surgeon', 'bones'),
('Orthopedic Surgeon', 'fracture'),
('Orthopedic Surgeon', 'joint pain'),
('Orthopedic Surgeon', 'knee'),
('Orthopedic Surgeon', 'back pain'),
('Pediatrician', 'child'),
('Pediatrician', 'baby'),
('Pediatrician', 'infant'),
('Pediatrician', 'toddler'),
('Pediatrician', 'kids'),
('Pediatrician', 'newborn'),
('Pediatrician', 'vaccination'),
('Ophthalmologist', 'eye'),
('Ophthalmologist', 'eyes'),
('Ophthalmologist', 'vision'),
('Ophthalmologist', 'blurred vision'),
('Ophthalmologist', 'cataract'),
('Ophthalmologist', 'glaucoma'),
('Gynecologist', 'pregnancy'),
('Gynecologist', 'prenatal'),
('Gynecologist', 'period pain'),
('Gynecologist', 'menstrual'),
('Gynecologist', 'fertility'),
('Gynecologist', 'menopause'),
('Endocrinologist', 'diabetes'),
('Endocrinologist', 'sugar'),
('Endocrinologist', 'thyroid'),
('Endocrinologist', 'hormone'),
('Endocrinologist', 'high sugar'),
('Endocrinologist', 'low sugar'),
('Endocrinologist', 'blood sugar'),
('Endocrinologist', 'weight change'),
('Endocrinologist', 'hormone imbalance'),
('Endocrinologist', 'thyroid problem'),
('Dentist', 'dentist'),
('Dentist', 'tooth pain'),
('Dentist', 'teeth'),
('Dentist', 'tooth'),
('Dentist', 'gum pain'),
('Dentist', 'dental'),
('Dentist', 'cavity'),
('Dentist', 'tooth ache'),
('Dentist', 'pain in teeth'),
('Dentist', 'mouth pain'),
('Dentist', 'bad tooth'),
('Dentist', 'sore gum'),
('Dentist', 'gum swelling'),
('General Physician', 'fever'),
('General Physician', 'cough'),
('General Physician', 'cold'),
('General Physician', 'flu'),
('General Physician', 'infection'),
('General Physician', 'headache'),
('General Physician', 'body pain'),
('General Physician', 'sore throat'),
('General Physician', 'runny nose'),
('General Physician', 'common cold'),
('General Physician', 'stomach pain'),
('General Physician', 'stomach upset'),
('General Physician', 'fever in child'),
('Neurologist', 'migraine'),
('Neurologist', 'headache'),
('Neurologist', 'nerve'),
('Neurologist', 'seizure'),
('Neurologist', 'stroke'),
('Neurologist', 'dizziness'),
('Neurologist', 'numbness'),
('Neurologist', 'tingling'),
('Neurologist', 'weakness'),
('Neurologist', 'fainting'),
('Neurologist', 'head spinning'),
('Cardiologist', 'pain in chest'),
('Cardiologist', 'chest tightness'),
('Cardiologist', 'palpitations'),
('Cardiologist', 'fast heartbeat'),
('Cardiologist', 'heart flutter'),
('Cardiologist', 'heart attack'),
('Cardiologist', 'breathlessness'),
('Cardiologist', 'shortness of breath'),
('Dermatologist', 'skin problem'),
('Dermatologist', 'itchy skin'),
('Dermatologist', 'skin itching'),
('Dermatologist', 'red spots'),
('Dermatologist', 'spots on skin'),
('Dermatologist', 'dry skin'),
('Dermatologist', 'rashes'),
('Dermatologist', 'skin allergy'),
('Dermatologist', 'face acne'),
('Dermatologist', 'pimple on face'),
('Orthopedic Surgeon', 'broken arm'),
('Orthopedic Surgeon', 'broken leg'),
('Orthopedic Surgeon', 'sprain'),
('Orthopedic Surgeon', 'twisted ankle'),
('Orthopedic Surgeon', 'wrist pain'),
('Orthopedic Surgeon', 'arm pain'),
('Orthopedic Surgeon', 'leg pain'),
('Orthopedic Surgeon', 'slipped disc'),
('Pediatrician', 'child fever'),
('Pediatrician', 'kids cough'),
('Pediatrician', 'child cough'),
('Pediatrician', 'baby fever'),
('Pediatrician', 'newborn care'),
('Pediatrician', 'baby vaccination'),
('Pediatrician', 'child checkup'),
('Ophthalmologist', 'blurred eyesight'),
('Ophthalmologist', 'trouble seeing'),
('Ophthalmologist', 'eye pain'),
('Ophthalmologist', 'red eye'),
('Ophthalmologist', 'watery eyes'),
('Ophthalmologist', 'eye irritation'),
('Ophthalmologist', 'poor vision'),
('Gynecologist', 'missed period'),
('Gynecologist', 'period problem'),
('Gynecologist', 'monthly cycle'),
('Gynecologist', 'pregnancy test'),
('Gynecologist', 'trying to conceive'),
('Gynecologist', 'female issue');

CREATE TABLE IF NOT EXISTS doctor_schedule (
    schedule_id INT AUTO_INCREMENT PRIMARY KEY,
    doctor_id INT NOT NULL,
    day_of_week VARCHAR(15) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    slot_duration INT NOT NULL DEFAULT 30,
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointments (
    appointment_id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status ENUM('Pending','Approved','Cancelled','Completed') NOT NULL DEFAULT 'Pending',
    cancelled_by VARCHAR(20) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admin (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT IGNORE INTO admin (username, password) VALUES
('admin', '$2y$10$e0NRoL.uG7T7Kz08ejp7BuM1hcC1yTmrhO/5x6iHZp42Z7YdxtUxS');
